<?php

namespace ContainerUsxAxec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Slht_EtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Slht.Et' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Slht.Et'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mission' => ['privates', '.errored..service_locator.Slht.Et.App\\Entity\\Mission', NULL, 'Cannot autowire service ".service_locator.Slht.Et": it needs an instance of "App\\Entity\\Mission" but this type has been excluded in "config/services.yaml".'],
            'pdfGenerator' => ['privates', 'App\\Service\\PdfGenerator', 'getPdfGeneratorService', true],
        ], [
            'mission' => 'App\\Entity\\Mission',
            'pdfGenerator' => 'App\\Service\\PdfGenerator',
        ]);
    }
}
