<?php

namespace ContainerUsxAxec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZUbbOiaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zUbbOia' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zUbbOia'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidature' => ['privates', '.errored..service_locator.zUbbOia.App\\Entity\\Candidature', NULL, 'Cannot autowire service ".service_locator.zUbbOia": it needs an instance of "App\\Entity\\Candidature" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'candidature' => 'App\\Entity\\Candidature',
            'em' => '?',
        ]);
    }
}
