<?php

namespace ContainerUsxAxec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FiqNNQCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fiqNNQC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fiqNNQC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mission' => ['privates', '.errored..service_locator.fiqNNQC.App\\Entity\\Mission', NULL, 'Cannot autowire service ".service_locator.fiqNNQC": it needs an instance of "App\\Entity\\Mission" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'mission' => 'App\\Entity\\Mission',
        ]);
    }
}
