<?php

namespace ContainerUsxAxec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMissionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DzSeb2e.App\Entity\Mission' shared service.
     *
     * @return \App\Entity\Mission
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DzSeb2e": it needs an instance of "App\\Entity\\Mission" but this type has been excluded in "config/services.yaml".');
    }
}
