<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mission extends \App\Entity\Mission implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'budget' => [parent::class, 'budget', null, 16],
        "\0".parent::class."\0".'candidatures' => [parent::class, 'candidatures', null, 16],
        "\0".parent::class."\0".'competance' => [parent::class, 'competance', null, 16],
        "\0".parent::class."\0".'datePub' => [parent::class, 'datePub', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nbreUtilisateur' => [parent::class, 'nbreUtilisateur', null, 16],
        "\0".parent::class."\0".'nomEntreprise' => [parent::class, 'nomEntreprise', null, 16],
        "\0".parent::class."\0".'nombreCandidatures' => [parent::class, 'nombreCandidatures', null, 16],
        "\0".parent::class."\0".'questions' => [parent::class, 'questions', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        'budget' => [parent::class, 'budget', null, 16],
        'candidatures' => [parent::class, 'candidatures', null, 16],
        'competance' => [parent::class, 'competance', null, 16],
        'datePub' => [parent::class, 'datePub', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'duree' => [parent::class, 'duree', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nbreUtilisateur' => [parent::class, 'nbreUtilisateur', null, 16],
        'nomEntreprise' => [parent::class, 'nomEntreprise', null, 16],
        'nombreCandidatures' => [parent::class, 'nombreCandidatures', null, 16],
        'questions' => [parent::class, 'questions', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
