<?php

namespace ContainerSzEuhRs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SkfIa3WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.skfIa3W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.skfIa3W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'missionRepository' => ['privates', 'App\\Repository\\MissionRepository', 'getMissionRepositoryService', true],
        ], [
            'missionRepository' => 'App\\Repository\\MissionRepository',
        ]);
    }
}
