<?php

namespace ContainerSzEuhRs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JI2pQWAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jI2pQWA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jI2pQWA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CandidatureController::delete' => ['privates', '.service_locator.zUbbOia', 'get_ServiceLocator_ZUbbOiaService', true],
            'App\\Controller\\CandidatureController::edit' => ['privates', '.service_locator.zUbbOia', 'get_ServiceLocator_ZUbbOiaService', true],
            'App\\Controller\\CandidatureController::index' => ['privates', '.service_locator..T.uEDf', 'get_ServiceLocator__T_UEDfService', true],
            'App\\Controller\\CandidatureController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CandidatureController::show' => ['privates', '.service_locator.2qMMOxw', 'get_ServiceLocator_2qMMOxwService', true],
            'App\\Controller\\CandidatureController::showQrCode' => ['privates', '.service_locator.2qMMOxw', 'get_ServiceLocator_2qMMOxwService', true],
            'App\\Controller\\MissionController::delete' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController::edit' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController::generatePdf' => ['privates', '.service_locator.Slht.Et', 'get_ServiceLocator_Slht_EtService', true],
            'App\\Controller\\MissionController::index' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'App\\Controller\\MissionController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MissionController::show' => ['privates', '.service_locator.DzSeb2e', 'get_ServiceLocator_DzSeb2eService', true],
            'App\\Controller\\MissionSearchController::advancedSearch' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'App\\Controller\\MissionSearchController::search' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CandidatureController:delete' => ['privates', '.service_locator.zUbbOia', 'get_ServiceLocator_ZUbbOiaService', true],
            'App\\Controller\\CandidatureController:edit' => ['privates', '.service_locator.zUbbOia', 'get_ServiceLocator_ZUbbOiaService', true],
            'App\\Controller\\CandidatureController:index' => ['privates', '.service_locator..T.uEDf', 'get_ServiceLocator__T_UEDfService', true],
            'App\\Controller\\CandidatureController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CandidatureController:show' => ['privates', '.service_locator.2qMMOxw', 'get_ServiceLocator_2qMMOxwService', true],
            'App\\Controller\\CandidatureController:showQrCode' => ['privates', '.service_locator.2qMMOxw', 'get_ServiceLocator_2qMMOxwService', true],
            'App\\Controller\\MissionController:delete' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController:edit' => ['privates', '.service_locator.fiqNNQC', 'get_ServiceLocator_FiqNNQCService', true],
            'App\\Controller\\MissionController:generatePdf' => ['privates', '.service_locator.Slht.Et', 'get_ServiceLocator_Slht_EtService', true],
            'App\\Controller\\MissionController:index' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'App\\Controller\\MissionController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MissionController:show' => ['privates', '.service_locator.DzSeb2e', 'get_ServiceLocator_DzSeb2eService', true],
            'App\\Controller\\MissionSearchController:advancedSearch' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'App\\Controller\\MissionSearchController:search' => ['privates', '.service_locator.skfIa3W', 'get_ServiceLocator_SkfIa3WService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CandidatureController::delete' => '?',
            'App\\Controller\\CandidatureController::edit' => '?',
            'App\\Controller\\CandidatureController::index' => '?',
            'App\\Controller\\CandidatureController::new' => '?',
            'App\\Controller\\CandidatureController::show' => '?',
            'App\\Controller\\CandidatureController::showQrCode' => '?',
            'App\\Controller\\MissionController::delete' => '?',
            'App\\Controller\\MissionController::edit' => '?',
            'App\\Controller\\MissionController::generatePdf' => '?',
            'App\\Controller\\MissionController::index' => '?',
            'App\\Controller\\MissionController::new' => '?',
            'App\\Controller\\MissionController::show' => '?',
            'App\\Controller\\MissionSearchController::advancedSearch' => '?',
            'App\\Controller\\MissionSearchController::search' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CandidatureController:delete' => '?',
            'App\\Controller\\CandidatureController:edit' => '?',
            'App\\Controller\\CandidatureController:index' => '?',
            'App\\Controller\\CandidatureController:new' => '?',
            'App\\Controller\\CandidatureController:show' => '?',
            'App\\Controller\\CandidatureController:showQrCode' => '?',
            'App\\Controller\\MissionController:delete' => '?',
            'App\\Controller\\MissionController:edit' => '?',
            'App\\Controller\\MissionController:generatePdf' => '?',
            'App\\Controller\\MissionController:index' => '?',
            'App\\Controller\\MissionController:new' => '?',
            'App\\Controller\\MissionController:show' => '?',
            'App\\Controller\\MissionSearchController:advancedSearch' => '?',
            'App\\Controller\\MissionSearchController:search' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
