<?php

namespace ContainerSzEuhRs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2qMMOxw.App\Entity\Candidature' shared service.
     *
     * @return \App\Entity\Candidature
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2qMMOxw": it needs an instance of "App\\Entity\\Candidature" but this type has been excluded in "config/services.yaml".');
    }
}
