<?php

namespace ContainerSzEuhRs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrCodeGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QrCodeGenerator' shared autowired service.
     *
     * @return \App\Service\QrCodeGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'QrCodeGenerator.php';

        return $container->privates['App\\Service\\QrCodeGenerator'] = new \App\Service\QrCodeGenerator(($container->services['router'] ?? self::getRouterService($container)));
    }
}
