parameters:
    # Paramètres Twilio
    twilio.sid: '%env(TWILIO_SID)%'
    twilio.token: '%env(TWILIO_TOKEN)%'
    twilio.verify_service_sid: '%env(TWILIO_VERIFY_SID)%'
    twilio.dev_mode: '%env(bool:TWILIO_DEV_MODE)%'
    # Paramètres pour l'upload d'images
    profile_images_directory: '%kernel.project_dir%/public/uploads/profile_images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    # Configuration du service Twilio
    App\Service\TwilioService:
        arguments:
            $twilioSid: '%twilio.sid%'
            $twilioToken: '%twilio.token%'
            $twilioVerifyServiceSid: '%twilio.verify_service_sid%'
            $isDev: '%twilio.dev_mode%'
            
    # Configuration du service d'upload de fichiers
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%profile_images_directory%'
