<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUsxAxec\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUsxAxec/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUsxAxec.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUsxAxec\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUsxAxec\App_KernelDevDebugContainer([
    'container.build_hash' => 'UsxAxec',
    'container.build_id' => 'a72fd7f4',
    'container.build_time' => 1745837596,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUsxAxec');
